### PR TITLE
Unify deb creation on linux

### PR DESCRIPTION
**Pull request by ann0see**
This PR includes some commits from jamulussoftware/master. Sorry about that. 

The linux build scripts will probably need to be re-adapted to this.

### CODE REVIEW

**Comment by nefarius2001** [comment]
sorry, I saw this quite late

**Comment by ann0see** [comment]
No problem. Now the yaml file can be updated to have only one asset ;-).

**Comment by nefarius2001** [comment]
There was some conflict with the current matter, can you resolve that, please?

**Comment by ann0see** [comment]
> There was some conflict with the current matter, can you resolve that, please?

Just use the code from this PR. The conflict comes from a commit which applies a bug fix from here probably. I can look into it too if you want.

**Pull request merged**
